/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    ContextMenuContent: typeof import('radix-vue')['ContextMenuContent']
    ContextMenuItem: typeof import('radix-vue')['ContextMenuItem']
    ContextMenuPortal: typeof import('radix-vue')['ContextMenuPortal']
    ContextMenuRoot: typeof import('radix-vue')['ContextMenuRoot']
    ContextMenuSeparator: typeof import('radix-vue')['ContextMenuSeparator']
    ContextMenuTrigger: typeof import('radix-vue')['ContextMenuTrigger']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipArrow: typeof import('radix-vue')['TooltipArrow']
    TooltipContent: typeof import('radix-vue')['TooltipContent']
    TooltipPortal: typeof import('radix-vue')['TooltipPortal']
    TooltipProvider: typeof import('radix-vue')['TooltipProvider']
    TooltipRoot: typeof import('radix-vue')['TooltipRoot']
    TooltipTrigger: typeof import('radix-vue')['TooltipTrigger']
  }
}
